name: project_shift

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9

  # jupyter stack
  - ipython
  - jupyter
  - jupyterlab
  - ipykernel
  - nest-asyncio

  # core scientific stack (без жестких старых пинов)
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - plotly

  # data / parsing
  - requests
  - beautifulsoup4
  - nltk
  - regex

  # db
  - sqlalchemy
  - psycopg2

  # ML libs которые ты хочешь
  - catboost
  - shap

  - pip
